### ISSUE TITLE
Garrisoned HMG spawning beneath observation tower

### ISSUE THREAD

**Issue by Golbs** [rekterakathom/Overthrow#112]
**Describe the bug**
When purchasing a HMG in a friendly base through the Y -> Garrison interface the gun spawns beneath an available observation tower instead of up inside the tower.  This occurs 100% of the time in all bases and placed FOBs, in all locations and on all islands of Tanoa. This has occurred in tens of towers in my save.  

**To Reproduce**
1. Build observation towers in friendly base or FOB
2. Purchase static HMGs via Y -> Garrison menu

**Expected behavior**
The HMG should spawn placed inside the tower on the platform at top of the stairs orientated looking through the forward windows.

**Screenshots**
![image_2024-04-16_151350211](https://github.com/rekterakathom/Overthrow/assets/23619739/f0a91b77-86e1-49dd-a853-04365b1f5719)

**Additional context**
Garrisoned HMGs will place correctly on the roof of the large cargo towers and armoured HQ buildings.
Unknown if bug exists on other maps.

**Include a RPT file from the session the bug occurred in**
will need instructions on how to find the correct file.

**Comment by wriley** [comment]
This happens on Altis as well FWIW
