### ISSUE TITLE
Resistence Fund bugged

### ISSUE THREAD

**Issue by hayrikaptan** [rekterakathom/Overthrow#125]
**Describe the bug**
Since the latest update, I am unable to access the money in my account. My friends are also experiencing the same issue, as they are unable to send or receive money to or from my account, or even their own accounts. The issue started immediately after the most recent update.

**To Reproduce**
Open the app after the latest update.
Attempt to send money to your own account or to a friend’s account.
The transaction will fail, and no money will be transferred.
I create new save and its same.

**Expected behavior**
I expected to be able to send and receive money to and from my account without any issues, and my friends should also be able to transfer money to and from their accounts normally.

**Additional context**
My save is here :
`
[SaveData-Arma3.txt](https://github.com/user-attachments/files/17318587/SaveData-Arma3.txt)
`

**Comment by rekterakathom** [comment]
Should be fixed in 2.4.0.0, no reports of this bug in a while so I am closing this issue.
