### ISSUE TITLE
Unable to craft at the workbench

### ISSUE THREAD

**Issue by wriley** [rekterakathom/Overthrow#4]
Problem: Crafting at the workbench does nothing
Steps to reproduce:

1) Start a new game, skip the tutorial
2) Put your starting uniform in the ammo container
3) Select craft at the workbench
4) Select Bandage option and try to craft

Result: Sound effect but no message and no bandages

Expected result: Sound effect and bandages get crafted

Note: I have only tested this with the bandage recipe

**Comment by Tuupertunut** [comment]
When crafting, an error appears in the log
```
12:27:44 Error in expression <cipe","_qty"];

    _container = player nearestObject OT_item_Storage;
    if !(>
12:27:44   Error position: <nearestObject OT_item_Storage;
    if !(>
12:27:44   Error nearestobject: Type Object, expected Array
12:27:44 File /overthrow_main/functions/actions/fn_craft.sqf..., line 16
```
