### ISSUE TITLE
Discussion: Should we remove the single player missions?

### ISSUE THREAD

**Issue by Tuupertunut** [rekterakathom/Overthrow#44]
Should we remove the single player missions? Overthrow already complains that it does not work well if you start it in single player but the missions are there.

Pros:
- We don't need to maintain the same code in two different places.
- Some parts of the code may be simplified where there are multiplayer checks.

Cons:
- Maybe saves started in single player won't work anymore in multiplayer?

**Comment by rekterakathom** [comment]
I think this might be a good call.
