### ISSUE TITLE
NATO APCs will never return fire with their cannon or turret

### ISSUE THREAD

**Issue by StormCircuit** [rekterakathom/Overthrow#70]
This was an issue with the original overthrow which made it such that everytime NATO brought an APC we got a free APC just by removing the tires. At least this way they will help their allies:
https://github.com/rekterakathom/Overthrow/blob/master/addons/overthrow_main/functions/factions/NATO/fn_NATOAPCInsertion.sqf#L70

Changing CARELESS to SAFE in this file I believe will change the APC behavior. Setting it to safe allows for them to drive full speed AND engage an enemy if they see one. Seems like it makes more sense to me.

**Comment by rekterakathom** [comment]
Thanks for reporting and proposing a solution. I'll include this fix in the next release
