### ISSUE TITLE
Add UAV Hacking by giving players UAV hacking trait

### ISSUE THREAD

**Issue by StormCircuit** [rekterakathom/Overthrow#83]
Can I just edit the mission file and upload it as a new version for a PR? Or would that cause problems, I figure you might have edits you need to make and we may overwrite each other.

**Comment by rekterakathom** [comment]
The mission file change might not work properly with respawns. I am not sure if the trait would carry over when respawning, so what I am going to do instead is add the trait in ``fn_setupPlayer.sqf`` so respawns aren't an issue.
