### ISSUE TITLE
Spaces in .bisign seem to be breaking the signature check

### ISSUE THREAD

**Issue by MrDj200** [rekterakathom/Overthrow#99]
The spaces you use in 
`overthrow_main.pbo.Overthrow Community Edition-2.2.0.0.bisign`
seem to be breaking a lot of compatibility on linux dedicated servers.

Furthermore, the .bikey file should be called `overthrow_community_edition-2.2.0.0` (or similar).
All mods I went through to compare against had their naming scheme of the key files like this.

I don't have hard evidence of this being the cause of my issue, but I know that incorrectly named things have broken my game in the past.

In case I'm totally wrong, please tell me why we get a key mismatch when joining my server, even though the key is in the keys folder and the A3 Launcher also says it's fine.

**Comment by rekterakathom** [comment]
I use a tool called HEMTT to build the addon, so the key generation is completely automated. The same tool (albeit a different version) is used to build both CBA and ACE. I have not received any messages regarding any of the other mods I've released about this issue, despite the ``.bisign`` suffix not matching the name of the ``.bikey`` perfectly.

I have reached out to the Arma discord to confirm whether or not the current keys are valid, and the keys will be named differently in the next release to accomodate linux users.

**Comment by MrDj200** [comment]
As I said, it's just an observation I made, so I can't be 100% sure, since the arma logs seem to be useless as well in this case.
I'm looking forward to trying it in the next release!

**Comment by rekterakathom** [comment]
Small status update: The keys are indeed invalid despite the publisher and launcher saying otherwise (Dedmen said something somewhere about some signature checks being outdated...)

So far no (good) fix has been found

**Comment by MrDj200** [comment]
Is there anything I can do to make it run on my server, or do I just wait for a new release?

**Comment by rekterakathom** [comment]
Fixed in latest release
